### ISSUE TITLE
Compatibility with older environments

### ISSUE THREAD

**Issue by pdulapalli** [asfktz/Awaity.js#9]
Hello,

I was wondering. Would it be possible to use your library on an older runtime, like Node v4?

You use a few `async` functions for some reason in your library itself. I'm not sure if that choice breaks compatibility with Promise-based but not async/await ready versions.

**Comment by asfktz** [comment]
Hi @pdulapalli (:

I haven't tested it against node 4 but it should work.
I've only used async/await in tests, not in the library itself.
Can you show me the errors you get?

**Comment by pdulapalli** [comment]
Hello!

Thanks so much for responding. Yeah, I noticed that only the tests used async/await. 

Here's the thing...I don't get any errors. I'm using Node v4.2.2 and I only used the `map` function. This hasn't caused me any issues, but I'm not sure if it's because Node is failing silently.

By the way, you should be able to easily test older Node versions using the [Node Version Manager](https://github.com/creationix/nvm). If the `npm install` step and other steps work well for you, then I think we're good to go. Of course, the async/await will fail. 

On a side note, would you be opposed to me eventually submitting a PR that creates Promise-based tests as opposed to async/await syntax?

**Comment by asfktz** [comment]
Oh, that makes sense 😄
The thing is, tests are only relevant for development, so they aren't actually running on your machine unless you run them manually.

Thanks for offer, I appreciate it a lot 🙏
I think it would not be necessary because now that I think about it, the test should work on node 4 too because I transpile them with [Babel](http://babeljs.io).

Mind to run `npm test` on node 4 to see if all work as expected? (:

I plan to set up a CI which will run the tests on different environments every time a change made to the codebase.

I can use some hand with that if you like this kind of stuff (:
